### ISSUE TITLE
[Vulnerability] Proper expiration for jwtToken cookie in browser

### ISSUE THREAD

**Issue by AmplifiedHuman** [rajitbanerjee/vax-warden#77]
- implement using Spring Security

**Comment by rajitbanerjee** [comment]
Updates:
- https://github.com/auth0/java-jwt already sets a sensible expiration time for json web token in the backend. The bug here is only frontend related.
- Easy fix: switch from `localStorage` to `sessionStorage` to clear jwtToken when changing tabs or browser window.
